export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <ul>
            <li>Home</li>
            <li>Analytic</li>
            <li>Setting</li>
          </ul>
          {children}
        </>
      </body>
    </html>
  );
}
