export const metadata = {
  title: "Create Setting",
  description: "Generated by create Setting",
};

const Setting = () => {
  return (
    <div>
      <h2>Analytics</h2>
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel iure
        beatae rem, pariatur ut illo numquam obcaecati excepturi, atque eum
        quam. Ipsa facilis accusamus quidem excepturi nesciunt, autem quos sed!
      </p>
    </div>
  );
};

export default Setting;
